### ISSUE TITLE
Remove feature after upload

### ISSUE THREAD

**Issue by anikets43** [ptkach/fileDroppa#49]
Hi @ptkach 
Is it possible to have features like gmail file upload. When we upload files, it auto-post to the server but retain the files to delete later if required.
I will return the File ID and assign it to the file tile remove button after file uploads. When user wants to delete the saved one, we will have FIleID. OnRemove, we again will have http call to delete the saved one.
![image](https://cloud.githubusercontent.com/assets/7136799/14551955/f5e26bb2-02f6-11e6-8793-c53bf1f2c1ac.png)

Thanks,
Aniket

**Comment by ptkach** [comment]
Hi, thank you. That's very good idea. Let me try to implement it during the weekend. Let me know if you would like to contribute.

**Comment by anikets43** [comment]
Hi @ptkach 
Thanks for considering my input. 
I'm going through your code. I would be glad to help you. Please let me know.

Cheers,
Aniket

**Comment by anikets43** [comment]
Hi @ptkach 

Any progress on this?

Regards,
Aniket

**Comment by ptkach** [comment]
Hi,

Not really, I have spent a bit of time now to upgrade all dependencies and make sure everything works fine. And now can start working on it. I will revert to you tomorrow with some result.

Sorry for delay.

**Comment by ptkach** [comment]
Hi @anikets43,

I had a chance to spend some time today on it. It's quite close to be fixed. But I think I would need your help. 

What I did as of now is added configuration to now remove automatically when file uploaded and added in File.ts logic to check if file was uploaded successfully or not. Based on that it generates div with just a Remove or Retry text. On Remove click it makes DELETE request with this file - I don't see any reason to pass id file back and fort, lets do it this way for now and move it to if in future.

If you have time tomorrow can you help me with styles for it and polish this logic, because unfortunately I'm not able to spend a lot of time on it now.

I will really appreciate your help.

Thanks,
Pavlo

**Comment by anikets43** [comment]
Hi @ptkach 
Sure, let me know I will be available this weekend.

Thanks,
Aniket

**Comment by ptkach** [comment]
Hi @anikets43,

Sounds good, open PR once your have something to add and don't hesitate to asking if you have any questions regarding code

**Comment by anikets43** [comment]
Hi @ptkach 

I have some queries/suggestion.
1. Move the inline styles to separate css file. This will easier to override the styles.

2. When `removeWhenUploaded: false` and `autoUpload:true` is set to false in the configuration, it retains the file and shows one div with remove text. When clicked on that, then it is replaced by retry text. Below code is confusing me.

` <div *ngIf="uploadingClass()==='uploaded'" [ngStyle]="{cursor:'pointer'}" (click)="removeFileFromServer()">Remove</div>
<div (click)="removeFileFromServer()" *ngIf="uploadingClass()==='failed'" [ngStyle]="{cursor:'pointer'}">Retry</div>`
Both Remove and retry are calling same method.

3. As u mentioned that we need not to send the file id back and forth, then how we would be able to know which file has to be deleted when we are uploading multiple at a time with autoupload set to true.

4. Also, for remove file, it should have different api url. Where we are configuring that. I see 'onRemoveFileFromServer' method has been exposed and it is not working. 

5. Make image preview configurable. All the files in the list should have same behavior. 

Please feel free to contact me anytime. 
Let's make this the best ng2 file uploader :)

I am digging into the code and trying to understand how we make this better.

Appreciate your efforts.
Regards,
Aniket

**Comment by anikets43** [comment]
I have written Restful api for file deletion. It works fine to me when Remove/Retry is clicked. It sends the file itself to the server and from there we can delete the file matching the name. But let's say I have identical file names or same file for different users and I have to delete logically instead of hard deletion. That's the reason I have suggested to return the id back and assign div and when that div is clicked it will carry the file id and file(optionally).

Hope I make sense.

**Comment by ptkach** [comment]
Hi @anikets43, answers to your questions:

-> Move the inline styles to separate css file. This will easier to override the styles.
**It's not a problem at all, can be easily done**

-> When removeWhenUploaded: false and autoUpload:true is set to false in the configuration, it retains the file and shows one div with remove text. When clicked on that, then it is replaced by retry text. Below code is confusing me.

<div *ngIf="uploadingClass()==='uploaded'" [ngStyle]="{cursor:'pointer'}" (click)="removeFileFromServer()">Remove</div>
<div (click)="removeFileFromServer()" *ngIf="uploadingClass()==='failed'" [ngStyle]="{cursor:'pointer'}">Retry</div>
Both Remove and retry are calling same method.
**Yes, that was done just in sake of developement/testing purposes. Will be remove/refactored once we fugure our the way we gonna do it**

-> As u mentioned that we need not to send the file id back and forth, then how we would be able to know which file has to be deleted when we are uploading multiple at a time with autoupload set to true.
**What's comnfusing me with id is that someone will responde with id, someone will need to retain staus and he will need to add an id as well and we will need to have ability to adjust to every type of response people do**

-> Also, for remove file, it should have different api url. Where we are configuring that. I see 'onRemoveFileFromServer' method has been exposed and it is not working.
**We can set delete url in config, but as of now it takes the same url that used to upload and just makes it DELETE type instead of POST**

-> Make image preview configurable. All the files in the list should have same behavior.
**Not really understand what you mean, but I definatelly agree that file in file list should be redesigned. That's exactly what I meant when I was telling you that I need you help with styles**

Thanks for your significant and valuable response @anikets43. 
I believe we can make it really better now.

Best Regards,
Pavlo

**Comment by anikets43** [comment]
Hi @ptkach 

This is how I redesigned the file list. I have panel with less width so file name and progress bar are placed in two rows. I will make sure that everything accommodates in the same row. Let me know if you have anything to add.

![file-upload design](https://cloud.githubusercontent.com/assets/7136799/14763051/446b2442-09a8-11e6-9162-cf8218297cfd.png)

->Make image preview configurable. All the files in the list should have same behavior.
**When the uploaded file is image, it shows image preview in the file list. It would be good if you make it configurable to let developer decides based on the need.**

Also, I found that after the file is deleted the corresponding file from the list doesn't disappear. Please verify.

Cheers,
Anilket

**Comment by ptkach** [comment]
Hey @anikets43 

It looks amazing, you've done a great job!! Thanks a lot. 

What about preview, there're browser limitation taking place. Only images get be previewed displayed as a preview icon, that's why I did my best to give as much as possible useful information. 

I checked my version and files are deleted from the list once you click remove button. Maybe you have some changes that affects it?

P.S.: Nice music =)

Cheers,
Pavlo

**Comment by ptkach** [comment]
Hi @anikets43,

Do you have any progress on it?

**Comment by anikets43** [comment]
Hi @ptkach 
Sorry for the delay. I will commit the changes by tomorrow.

**Comment by anikets43** [comment]
Hi @ptkach 

There is some issue with package.json. I cloned the repo and did `npm install`. Found that prepublish script was creating some issue, so I removed and again tried. It installed all the dependencies but `npm start` is not working.
Here's npm log.

[npm-debug.txt](https://github.com/ptkach/fileDroppa/files/241093/npm-debug.txt)

**Comment by ptkach** [comment]
Hey @anikets43,

Thanks, it was problem with conflicted dependencies. Try it now, please!

**Comment by anikets43** [comment]
Hi @ptkach 

Still not able to run the application.
Here's attached error log.

[npm-debug.txt](https://github.com/ptkach/fileDroppa/files/245621/npm-debug.txt)

**Comment by ptkach** [comment]
Hi, 

As I see your fork is not up to date with master upstream. Please make sure you pick existing upstream master, install all drops and start server. 

I tested it on two separate environments and it works perfectly well.

**Comment by anikets43** [comment]
Hi, I downloaded the zipped file on my other windows system and installed the dependencies. Still issue with npm start.

**Comment by ptkach** [comment]
Hi, please tell me your nose and npm versions?

**Comment by ptkach** [comment]
Hey @anikets43,

I've updated all dependencies to the latest versions, I've added support for the last Node.js version (6.0.0) and NPM (3.8.6) and fixed all issues I had because of that. Please checkout master with latest changes, update you node and npm and it should be up and running after that. 

Please try to do it ASAP because I was expecting to finish with this issue long time before. Current master file-list doesn't look pretty nice and was thinking that we would need just a couple days to get nice and smoothy. 

Let me know if you still have any issues.

Best Regards,
Pavlo

**Comment by Antyneskul** [comment]
I've tried on node v6.0 and have no issues or any errors.
But, when I tried with node v5.7.0 - I've seen a lot of typescript errors - 

> 'error TS2375: Duplicate number index signature.'

**Comment by ptkach** [comment]
Hi @anikets43 ,

Please respond about your progress? Did you manage to start it?

Best Regards,
Pavlo

**Comment by anikets43** [comment]
Hi
I did try to install the packages but faced issue again. Let me try me again in the morning. Will close this weekend

On Fri, May 06, 2016 at 9:02 PM, Pavlo Tkach <notifications@github.com> wrote:



Hi @anikets43 ,
Please respond about your progress? Did you manage to start it?
Best Regards,
Pavlo
�
You are receiving this because you were mentioned.
Reply to this email directly or 
view it on GitHub





DISCLAIMER: This email message and all attachments are confidential and may contain information that is Privileged, Confidential or exempt from disclosure under applicable law. If you are not the intended recipient, you are notified that any dissemination, distribution or copying of this email is strictly prohibited.  If you have received this email in error, please notify us immediately by return email to mailadmin@spanservices.com and destroy the original message.  Opinions, conclusions and other information in this message that do not relate to the official of SPAN, shall be understood to be neither given nor endorsed by SPAN.

**Comment by anikets43** [comment]
@ptkach 

IIS was running on port 8080. My bad :(

**Comment by ptkach** [comment]
Commits are reverted, issue is closed since no interest to it from issue creator
