### ISSUE TITLE
Question: Uploading to a service

### ISSUE THREAD

**Issue by johntzan** [ptkach/fileDroppa#62]
Is it possible to upload the images to a service like Cloudinary? If not is there a way to override the upload files button click and use the files elsewhere Or is that only directly linked to the [url] parameter?

Thanks

**Comment by ptkach** [comment]
Hi @johntzan ,

First of all beforeRequest hook is available where you get xhr as a parameter. You can update it according to API of external service.

If it's not covering you needs - I can provide ability to override upload service at all. 
Please let me know if sounds good for you.

**Comment by johntzan** [comment]
I think what is here now works, but how can i edit the formData for the file that is uploaded. I need to make name="file" for the file being sent and remove filename? i see the beforeFileUpload method, where i can set my other formData requirements properly there, but cant edit the files

**Comment by ptkach** [comment]
I got your point. Since as a parameter in beforeFileUpload you retrieve formData object you can manipulating formData API set replace formData key and return modified formData object which will be send to url given. 

Something like this:

```javascript
beforeFileUpload(){
   const YOUR_formData = new FormData();
   for (let key of formData.keys()) {
      const file = formData.get('key');// Returns file
      YOUR_formData.append('YOUR_KEY', file);
   }
   return YOUR_formData;
}
```

It's not very nice, but at least you don't need to make any changes in node_modules. I will try to figure out how to fulfill your needs with something more clear later. 

Let me know if it helps and I will close this issue.

**Comment by johntzan** [comment]
Yup this worked! Only thing that needed changing was:

`const file = formData.get(key);// Returns file`

Letting key be taken from the loop and not the string 'key'.
