### ISSUE TITLE
Unexpected value 'FileDroppa' imported by the module 'AppModule' in ng2.0.0 release

### ISSUE THREAD

**Issue by trezero** [ptkach/fileDroppa#64]
This was working great in the NG2 RC's up to RC5 but as of RC6 and now in the 2.0.0 release I always get this error on application load. Even if I start with a fresh project with no other modules.

metadata_resolver.js:230 Uncaught Error: Unexpected value 'FileDroppa' imported by the module 'AppModule'

**Comment by ptkach** [comment]
Hi,

Thank you for reporting. This issue is related to angular2 release version and webpack version. There're already several issues like that reported regarding custom modules for angular2. I will try to investigate it deeper and find solution. As of now you can refer to demo folder for working example which works perfectly fine with rc.7. 

I will keep this issue open and I guess I will fix it in next few days.

**Comment by trezero** [comment]
I'm currently running Angular2.0.0 and Webpack 2.1.0-beta.22. Thanks for checking it out.

**Comment by ptkach** [comment]
Hi @trezero,

I've fixed this issue. It works now for me with angular2-seed with file-droppa installed. Please try to reinstall lib from npm and let me know how it goes.
